// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxwvucdknzeybmsyabwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4d3Z1Y2RrbnpleWJtc3lhYndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzAxMjcsImV4cCI6MjA3NDU0NjEyN30.e03KGJHJjDcDSeB7Ag9JDUrQC-_WRqWxeZ30-G8IQYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});